### ISSUE TITLE
ISO Duration rejects valid durations

### ISSUE THREAD

**Issue by FeLungs** [yetanalytics/xapi-schema#63]
`(clojure.spec.alpha/valid? :xapi-schema.spec/duration "PT3H25.51S")` -> false

`(clojure.spec.alpha/valid? :xapi-schema.spec/duration "PT3H0M25.51S")` -> true

It seems like the regex doesn't like hours and seconds without minutes but it should have no problem with this

**Comment by kelvinqian00** [comment]
Can you please confirm this? Having hours and seconds without minutes doesn't seem to be allowed under [ISO 8601](https://www.w3.org/TR/NOTE-datetime).

Also, doesn't [RFC 3339](https://tools.ietf.org/html/rfc3339#ref-ISO8601) specify that hours, minutes, and seconds should be separated using colons, rather than `H`, `M`, and `S`, respectively?

**Comment by kelvinqian00** [comment]
Fixed in PR #71
